# Page settings

baseURL = "https://marcin-dudek.github.io/resume"
languageCode = "en"
title = "Marcin Dudek Resume"
theme = "resume-theme"
googleAnalytics = "G-B81J6WSQJR"






[params]
    author = "marcin-dudek"
    description = "MarcinDudek resume based on DevResume"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Marcin Dudek"
        tagline = "Software Engineer/Architect"
        #avatar = "avatar.png"







    [params.contact]
        enable = true
        location = "Wroclaw, Poland"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "+48 507 865 812"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "marcin.dudek@outlook.com"
        # [[params.contact.list]]
        # icon = "fas fa-globe"
        # url = "#"
        # text = "www.yourwebsite.com"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "JavaScript/Angular/React/Vue"
        [[params.skills.list.items]]
        details = "Python/Ruby/PHP"
        [[params.skills.list.items]]
        details = "Node.js/ASP.NET"
        [[params.skills.list.items]]
        details = "PostgreSQL/MySQL"
        [[params.skills.list.items]]
        details = "Object-oriented design"
        [[params.skills.list.items]]
        details = "Design and implement database structures"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "MSc in Computer Science"
        university = "Technical University of Wroclaw"
        dates = "2004 - 2010"








    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Azure Solutions Architect Expert"
        body = "Microsoft"
        date = "2021"
        [[params.awards.list]]
        name = "AWS Solutions Architect Associate"
        body = "Amazon"
        date = "2020"
        [[params.awards.list]]
        name = "Terchnology Architect"
        body = "Avanade"
        date = "2020"







    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Professional"
        [[params.languages.list]]
        name = "Polish"
        level = "Native"
        [[params.languages.list]]
        name = "German"
        level = "Basic"








    [params.interests]
        enable = false

        [[params.interests.list]]
        name = "Gaming"
        [[params.interests.list]]
        name = "Learning new stuff"








    [params.summary]
        enable = true
        text = "I'm consultant experienced in designing and building modern applications. \n I believe in building simple software which delivers business value. Throughout my career took various roles always trying to challenge myself and improve not only technical aspects but also people skills. Recently working as Software Architect focused on Azure and CI/CD, building secure cloud native integrations."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Cloud Solution Architect"
        dates = "Jun 2020 · present"
        company = "Avanade"
        details = ""

        [[params.experience.list]]
        title = "SISA Architect"
        dates = "Jan 2022 · present"
        company = "Avanade"
        details = ""

        [[params.experience.list]]
        title = "Frontend Developer"
        dates = "Mar 2020 · May 2020"
        company = "Avanade"
        details = ""

        [[params.experience.list]]
        title = "Project Lead/Tech Lead"
        dates = "Sep 2018 · Mar 2020"
        company = "Avanade"
        details = "One of the world's largest pharmaceutical companies. The company develops and produces medicines and vaccines for a wide range of medical disciplines. Client engaged Avanade to build multiple applications for the Operations Centers which enable digital collaboration, standardization of manufacturing processes and provide insights into those."
        [[params.experience.list.items]]
        details = "Managing team of 20+ developers and QAs"
        [[params.experience.list.items]]
        details = "Helping shaping priorities and lead successful delivery, helping improving processes"
        [[params.experience.list.items]]
        details = "Helping shaping and execute microservice architecture"
        [[params.experience.list.items]]
        details = "Proposing technologies, tools and frameworks, helping client optimize infrastructure costs"
        [[params.experience.list.items]]
        details = "Creating and improving continues integration and continues development for application and services"
        [[params.experience.list.items]]
        details = "Azure DevOps, Docker, Kubernetes, C#, .NET Core, Git, PowerShell, awk"
        
        [[params.experience.list]]
        title = "Team Lead/Tech Lead"
        dates = "Sep 2018 · Mar 2020"
        company = "Avanade"
        details = "One of the world's largest pharmaceutical companies. The company develops and produces medicines and vaccines for a wide range of medical disciplines. Client engaged Avanade to build multiple applications for the Operations Centers which enable digital collaboration, standardization of manufacturing processes and provide insights into those."
        [[params.experience.list.items]]
        details = "Leading team of 5+ developers and QAs"
        [[params.experience.list.items]]
        details = "Discussing team priorities, shaping sprints, monitoring and reporting progress, requirements clarification, helping improving processes"
        [[params.experience.list.items]]
        details = "Shaping and execute microservice architecture"
        [[params.experience.list.items]]
        details = "Helping picking up tools and frameworks for project"
        [[params.experience.list.items]]
        details = "Creating and improving continues integration and continues development for application and services"
        [[params.experience.list.items]]
        details = "Tech: C#, .NET Core, Azure DevOps, Docker, Kubernetes, Git, PowerShell, XUnit, NSubstitute, UWP"

        [[params.experience.list]]
        title = "Senior Consultant"
        dates = "Aug 2016 · Sep 2017"
        company = "Infusion"
        details = "Developer in electronic-trading business which is used to execute orders on behalf of clients in Equities, Listed Derivatives (Futures and Options) and FX markets around the globe. Team is responsible for delivery of all technical aspects of the platform, the core framework and supporting services and tools."
        [[params.experience.list.items]]
        details = "Creating and designing framework to write scenarios for acceptance and regression testing."
        [[params.experience.list.items]]
        details = "Creating and improving CI/CD process for applications."
        [[params.experience.list.items]]
        details = "Development and maintenance of electronic trading and ticket routing applications."
        [[params.experience.list.items]]
        details = "Tech: C#, .NET 4.6, Moq, NUnit, TeamCity, DryIoC, LBM Messaging, Specflow, Powershell, Octopus"

        [[params.experience.list]]
        title = "Senior Consultant"
        dates = "Jan 2016 · Aug 2016"
        company = "Infusion"
        details = "Involved in development of Strategic Risk Systems under one vertical stack and code base, in conjunction with building common interfaces to the new stack."
        [[params.experience.list.items]]
        details = "Development web application for batch monitoring."
        [[params.experience.list.items]]
        details = "Implementation of a common set of libraries used for feeding data in multiple risk systems."
        [[params.experience.list.items]]
        details = "Tech: C#, .NET, Autofac, Windows Services, FakeItEasy, WCF, WebAPI, AngularJS, JavaScript, TypeScript, CSS"

        [[params.experience.list]]
        title = "Consultant"
        dates = "Nov 2013 · Dec 2015"
        company = "Infusion"
        details = "Engaged to help design, build and deliver components of distributed risk calculation engine. It consists of several major subsystems i.e. WCF services, distributed calculation processes and distributed cache."
        [[params.experience.list.items]]
        details = "Optimized build and deployment process with our application and decrease time from commit to deploy to environment."
        [[params.experience.list.items]]
        details = "Implementated and maintenaned Addin for Excel which allowed to retrieve data from REST service."
        [[params.experience.list.items]]
        details = "Designed and implementated authorization in framework used in several WCF services"
        [[params.experience.list.items]]
        details = "Tech: C#, .NET 4.0, NUnit, Rhino Mocks, Entity Framework, Tibco EMS, WCF, SQL Server 2008, SASS"

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "Jun 2012 · Oct 2013"
        company = "Jetshop"
        details = "Developing and maintaining e-commerce platform with administration application. Implementation SEO focused changes."
        [[params.experience.list.items]]
        details = "Tech: ASP.NET 3.5/4.0, jQuery, NUnit, Moq, SQL Server 2008"

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "Jul 2009 · May 2012"
        company = "Tieto Poland"
        details = "Developing and maintaining Windows applications for leading phone manufacturer. Design and development framework like components for windows applications, with strong focus on testability and composable design."
        [[params.experience.list.items]]
        details = "Tech: .NET Framework 2.0/3.5, NUnit, TypeMock Isolator "

        [[params.experience.list]]
        title = "Software Developer"
        dates = "Feb 2008 · Jun 2009"
        company = "anixe Poland"
        details = "Developing and maintaining web application for LOT - Polish airlines. Integrated standalone insurance booking system."
        [[params.experience.list.items]]
        details = "Tech: .NET Framework 1.1/2.0, ASP.NET, XML, XSL, XSLT, jQuery"



    [params.projects]
        enable = false

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."


    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"


    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/marcin-dudek"
        title = "marcin-dudek"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/dudekmarcin"
        title = "marcin-dudek"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/manekd"
        title = "@manekd"


